### ISSUE TITLE
怎么播放https开头的视频 

### ISSUE THREAD

**Issue by ZhetengDashen** [Jzvd/JZVideo#135]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
可以忽略https证书



---原始邮件---
发件人: "ZheTeng"<notifications@github.com&gt;
发送时间: 2020年5月8日(周五) 下午2:28
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 怎么播放https开头的视频  (#135)




 
**需求描述
 
**其他app是否实现
 
**截图或者小视频说明

**Comment by ZhetengDashen** [comment]
> 
> 可以忽略https证书
> […](#)
> ---原始邮件--- 发件人: "ZheTeng"<notifications@github.com&gt; 发送时间: 2020年5月8日(周五) 下午2:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 怎么播放https开头的视频 (#135) **需求描述 **其他app是否实现 **截图或者小视频说明 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

怎么设置啊

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/655




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZheTeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午2:05
收件人:&nbsp;"Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"李盼"<1066666651@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Jzvd/JiaoZiVideoPlayer] 怎么播放https开头的视频  (#135)





  
可以忽略https证书
 …
 ---原始邮件--- 发件人: "ZheTeng"<notifications@github.com&gt; 发送时间: 2020年5月8日(周五) 下午2:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 怎么播放https开头的视频 (#135) **需求描述 **其他app是否实现 **截图或者小视频说明 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
怎么设置啊

**Comment by CLZ666** [comment]
> [lipangit/JiaoZiVideoPlayer#655](https://github.com/lipangit/JiaoZiVideoPlayer/issues/655)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ZheTeng"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月11日(星期一) 下午2:05 收件人:&nbsp;"Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送:&nbsp;"李盼"<1066666651@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Jzvd/JiaoZiVideoPlayer] 怎么播放https开头的视频 (#135) 可以忽略https证书 … ---原始邮件--- 发件人: "ZheTeng"<notifications@github.com&gt; 发送时间: 2020年5月8日(周五) 下午2:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 怎么播放https开头的视频 (#135) **需求描述 **其他app是否实现 **截图或者小视频说明 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 怎么设置啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

怎么忽略呀
