### ISSUE TITLE
使用IJK播放音频地址，状态不对

### ISSUE THREAD

**Issue by BaiShou** [Jzvd/JZVideo#160]
**什么jzvd版本
7.4.1
**什么播放器内核
IJKPLAYER
**相关log是什么
播放纯音频文件，URL中不包含后缀,导致`onPrepared`方法中没有执行`onStatePlaying`。
**demo是否有这个问题
有
**自己做了哪些修改
解决办法添加相应的what。
`onInfo`方法中添加判断

`if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) {`
改为
`if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START || what == 10002) {`

int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始整备中

**如何操作复现
使用一个不带后缀的MP3地址
**什么安卓版本，什么机型
小米note3 ,android9
**截图或者视频说明情况

**Comment by lipangit** [comment]
可以&amp;mp3配置一下&nbsp; &nbsp;总之要让播放器识别mp3，因为和视频的ui不同



---原始邮件---
发件人: "Arnold"<notifications@github.com&gt;
发送时间: 2020年6月9日(周二) 晚上8:28
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160)




 
**什么jzvd版本
 7.4.1
 **什么播放器内核
 IJKPLAYER
 **相关log是什么
 播放纯音频文件，URL中不包含后缀,导致onPrepared方法中没有执行onStatePlaying。
 **demo是否有这个问题
 有
 **自己做了哪些修改
 解决办法添加相应的what。
 onInfo方法中添加判断
 
if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) {
 改为
 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START || what == 10002) {
 
int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始整备中
 
**如何操作复现
 使用一个不带后缀的MP3地址
 **什么安卓版本，什么机型
 小米note3 ,android9
 **截图或者视频说明情况

**Comment by BaiShou** [comment]
> 可以&amp;mp3配置一下&nbsp; &nbsp;总之要让播放器识别mp3，因为和视频的ui不同
> […](#)
> ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月9日(周二) 晚上8:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) **什么jzvd版本 7.4.1 **什么播放器内核 IJKPLAYER **相关log是什么 播放纯音频文件，URL中不包含后缀,导致onPrepared方法中没有执行onStatePlaying。 **demo是否有这个问题 有 **自己做了哪些修改 解决办法添加相应的what。 onInfo方法中添加判断 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) { 改为 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START || what == 10002) { int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始整备中 **如何操作复现 使用一个不带后缀的MP3地址 **什么安卓版本，什么机型 小米note3 ,android9 **截图或者视频说明情况 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

但是这样还有一个问题
` onInfo(int what, int extra) ` 方法中
if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START)
会先执行，导致
`onStatePlaying`方法中的
`if (state == STATE_PREPARED) {`
条件进不去

**Comment by lipangit** [comment]
先按照我的思路做，看在demo中是否行得通



---原始邮件---
发件人: "Arnold"<notifications@github.com&gt;
发送时间: 2020年6月10日(周三) 上午10:23
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160)




  
可以&amp;mp3配置一下&nbsp; &nbsp;总之要让播放器识别mp3，因为和视频的ui不同
 …
 ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月9日(周二) 晚上8:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) **什么jzvd版本 7.4.1 **什么播放器内核 IJKPLAYER **相关log是什么 播放纯音频文件，URL中不包含后缀,导致onPrepared方法中没有执行onStatePlaying。 **demo是否有这个问题 有 **自己做了哪些修改 解决办法添加相应的what。 onInfo方法中添加判断 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) { 改为 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START || what == 10002) { int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始整备中 **如何操作复现 使用一个不带后缀的MP3地址 **什么安卓版本，什么机型 小米note3 ,android9 **截图或者视频说明情况 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
但是这样还有一个问题
 onInfo(int what, int extra) 方法中
 if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START)
 会先执行，导致
 onStatePlaying方法中的
 if (state == STATE_PREPARED) {
 条件进不去

**Comment by BaiShou** [comment]
> 先按照我的思路做，看在demo中是否行得通
> […](#)
> ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月10日(周三) 上午10:23 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) 可以&amp;mp3配置一下&nbsp; &nbsp;总之要让播放器识别mp3，因为和视频的ui不同 … ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月9日(周二) 晚上8:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) **什么jzvd版本 7.4.1 **什么播放器内核 IJKPLAYER **相关log是什么 播放纯音频文件，URL中不包含后缀,导致onPrepared方法中没有执行onStatePlaying。 **demo是否有这个问题 有 **自己做了哪些修改 解决办法添加相应的what。 onInfo方法中添加判断 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) { 改为 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START || what == 10002) { int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始整备中 **如何操作复现 使用一个不带后缀的MP3地址 **什么安卓版本，什么机型 小米note3 ,android9 **截图或者视频说明情况 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 但是这样还有一个问题 onInfo(int what, int extra) 方法中 if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START) 会先执行，导致 onStatePlaying方法中的 if (state == STATE_PREPARED) { 条件进不去 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

需要怎么做，我先试试

**Comment by lipangit** [comment]
连接中添加mp3的标识



---原始邮件---
发件人: "Arnold"<notifications@github.com&gt;
发送时间: 2020年6月10日(周三) 中午1:32
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160)




  
先按照我的思路做，看在demo中是否行得通
 …
 ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月10日(周三) 上午10:23 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) 可以&amp;mp3配置一下&nbsp; &nbsp;总之要让播放器识别mp3，因为和视频的ui不同 … ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月9日(周二) 晚上8:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) **什么jzvd版本 7.4.1 **什么播放器内核 IJKPLAYER **相关log是什么 播放纯音频文件，URL中不包含后缀,导致onPrepared方法中没有执行onStatePlaying。 **demo是否有这个问题 有 **自己做了哪些修改 解决办法添加相应的what。 onInfo方法中添加判断 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) { 改为 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START || what == 10002) { int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始整备中 **如何操作复现 使用一个不带后缀的MP3地址 **什么安卓版本，什么机型 小米note3 ,android9 **截图或者视频说明情况 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 但是这样还有一个问题 onInfo(int what, int extra) 方法中 if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START) 会先执行，导致 onStatePlaying方法中的 if (state == STATE_PREPARED) { 条件进不去 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
需要怎么做，我先试试

**Comment by BaiShou** [comment]
> 连接中添加mp3的标识
> […](#)
> ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月10日(周三) 中午1:32 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) 先按照我的思路做，看在demo中是否行得通 … ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月10日(周三) 上午10:23 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) 可以&amp;mp3配置一下&nbsp; &nbsp;总之要让播放器识别mp3，因为和视频的ui不同 … ---原始邮件--- 发件人: "Arnold"<notifications@github.com&gt; 发送时间: 2020年6月9日(周二) 晚上8:28 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 使用IJK播放音频地址，状态不对 (#160) **什么jzvd版本 7.4.1 **什么播放器内核 IJKPLAYER **相关log是什么 播放纯音频文件，URL中不包含后缀,导致onPrepared方法中没有执行onStatePlaying。 **demo是否有这个问题 有 **自己做了哪些修改 解决办法添加相应的what。 onInfo方法中添加判断 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) { 改为 if (what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START || what == 10002) { int MEDIA_INFO_AUDIO_RENDERING_START = 10002;//音频开始整备中 **如何操作复现 使用一个不带后缀的MP3地址 **什么安卓版本，什么机型 小米note3 ,android9 **截图或者视频说明情况 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 但是这样还有一个问题 onInfo(int what, int extra) 方法中 if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START) 会先执行，导致 onStatePlaying方法中的 if (state == STATE_PREPARED) { 条件进不去 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 需要怎么做，我先试试 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这样可行
