### ISSUE TITLE
Jzvd.releaseAllVideos()后再次播放当前视频，进度不是从保存的播放的

### ISSUE THREAD

**Issue by 857288218** [Jzvd/JZVideo#190]
**需求描述
demo的RecyclerViewActivity中，当正在播放的item不可见时执行Jzvd.releaseAllVideos()，然后继续播放这个视频，并不是从上次缓存的进度播放的，例：播放到15秒，上滑列表使播放的item不可见，然后滑回来继续播放，是从10秒开始播放的；另外一个问题，当拖动进度条快进后，进度条就不随着视频的播放前进了

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
复写onprogress函数参数是否正确



---原始邮件---
发件人: "857288218"<notifications@github.com&gt;
发送时间: 2020年6月30日(周二) 晚上7:59
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] Jzvd.releaseAllVideos()后再次播放当前视频，进度不是从保存的播放的 (#190)




 
**需求描述
 demo的RecyclerViewActivity中，当正在播放的item不可见时执行Jzvd.releaseAllVideos()，然后继续播放这个视频，并不是从上次缓存的进度播放的，例：播放到15秒，上滑列表使播放的item不可见，然后滑回来继续播放，是从10秒开始播放的；另外一个问题，当拖动进度条快进后，进度条就不随着视频的播放前进了
 
**其他app是否实现
 
**截图或者小视频说明

**Comment by 857288218** [comment]
> 复写onprogress函数参数是否正确
> […](#)
> ---原始邮件--- 发件人: "857288218"<notifications@github.com&gt; 发送时间: 2020年6月30日(周二) 晚上7:59 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JZVideo] Jzvd.releaseAllVideos()后再次播放当前视频，进度不是从保存的播放的 (#190) **需求描述 demo的RecyclerViewActivity中，当正在播放的item不可见时执行Jzvd.releaseAllVideos()，然后继续播放这个视频，并不是从上次缓存的进度播放的，例：播放到15秒，上滑列表使播放的item不可见，然后滑回来继续播放，是从10秒开始播放的；另外一个问题，当拖动进度条快进后，进度条就不随着视频的播放前进了 **其他app是否实现 **截图或者小视频说明 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

demo中就有这个问题，我没修改过代码

**Comment by 534365726** [comment]
Jzvd.releaseAllVideos()，后肯定不能继续播放了吧，可以看看文档中的关于按home停止播放，返回继续播放代码



---原始邮件---
发件人: "857288218"<notifications@github.com&gt;
发送时间: 2020年7月1日(周三) 中午11:41
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Jzvd/JZVideo] Jzvd.releaseAllVideos()后再次播放当前视频，进度不是从保存的播放的 (#190)




  
复写onprogress函数参数是否正确
 …
 ---原始邮件--- 发件人: "857288218"<notifications@github.com&gt; 发送时间: 2020年6月30日(周二) 晚上7:59 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JZVideo] Jzvd.releaseAllVideos()后再次播放当前视频，进度不是从保存的播放的 (#190) **需求描述 demo的RecyclerViewActivity中，当正在播放的item不可见时执行Jzvd.releaseAllVideos()，然后继续播放这个视频，并不是从上次缓存的进度播放的，例：播放到15秒，上滑列表使播放的item不可见，然后滑回来继续播放，是从10秒开始播放的；另外一个问题，当拖动进度条快进后，进度条就不随着视频的播放前进了 **其他app是否实现 **截图或者小视频说明 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
demo中就有这个问题，我没修改过代码

**Comment by 857288218** [comment]
> Jzvd.releaseAllVideos()，后肯定不能继续播放了吧，可以看看文档中的关于按home停止播放，返回继续播放代码
> […](#)
> ---原始邮件--- 发件人: "857288218"<notifications@github.com&gt; 发送时间: 2020年7月1日(周三) 中午11:41 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [Jzvd/JZVideo] Jzvd.releaseAllVideos()后再次播放当前视频，进度不是从保存的播放的 (#190) 复写onprogress函数参数是否正确 … ---原始邮件--- 发件人: "857288218"<notifications@github.com&gt; 发送时间: 2020年6月30日(周二) 晚上7:59 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JZVideo] Jzvd.releaseAllVideos()后再次播放当前视频，进度不是从保存的播放的 (#190) **需求描述 demo的RecyclerViewActivity中，当正在播放的item不可见时执行Jzvd.releaseAllVideos()，然后继续播放这个视频，并不是从上次缓存的进度播放的，例：播放到15秒，上滑列表使播放的item不可见，然后滑回来继续播放，是从10秒开始播放的；另外一个问题，当拖动进度条快进后，进度条就不随着视频的播放前进了 **其他app是否实现 **截图或者小视频说明 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. demo中就有这个问题，我没修改过代码 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

试着能继续播放，我看JZUtils中播放的进度存到sp了，不过继续播放的进度不对，sp中保存的是正确的

**Comment by lipangit** [comment]
保持关注，有时间研究一下

**Comment by MaiYiHang** [comment]
我也碰到了这个问题

**Comment by ithomasoft** [comment]
+1

**Comment by lipangit** [comment]
demo运行正常  首页的视频播放中切换tab，首页视频停止播放，然后回到首页点击播放，会继续从之前的进度

**Comment by ithomasoft** [comment]
> demo运行正常 首页的视频播放中切换tab，首页视频停止播放，然后回到首页点击播放，会继续从之前的进度播放

demo中自定义AGvideo不能保存播放进度
